# Generated by Django 3.2.9 on 2021-11-28 19:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('staff', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='staff',
            name='contact',
            field=models.IntegerField(null=True),
        ),
    ]
