# Generated by Django 3.2.9 on 2021-11-28 20:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('staff', '0002_alter_staff_contact'),
        ('patients', '0002_auto_20211129_0056'),
    ]

    operations = [
        migrations.AlterField(
            model_name='patient',
            name='treatment_category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='staff.specialities'),
        ),
    ]
