# Generated by Django 3.2.9 on 2021-11-29 13:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('patients', '0005_alter_patient_treatment_category'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='patient',
            name='treatment_category',
        ),
        migrations.AddField(
            model_name='patient',
            name='blood_group',
            field=models.CharField(choices=[('A+', 'A+'), ('B+', 'B+'), ('O+', 'O+'), ('AB+', 'AB+'), ('A-', 'A-'), ('B-', 'B-'), ('O-', 'O-'), ('AB-', 'AB-')], max_length=200, null=True),
        ),
    ]
