# Generated by Django 3.2.9 on 2021-11-29 21:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('patients', '0008_remove_meds_category'),
    ]

    operations = [
        migrations.AddField(
            model_name='meds',
            name='mowner',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='patients.patient'),
        ),
        migrations.AddField(
            model_name='tests',
            name='towner',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='patients.patient'),
        ),
        migrations.AlterField(
            model_name='tests',
            name='tname',
            field=models.CharField(max_length=200),
        ),
    ]
