# Generated by Django 3.2.9 on 2021-11-29 21:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('patients', '0009_auto_20211130_0314'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bills',
            name='owner',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='patients.patient'),
        ),
    ]
