# Generated by Django 3.2.9 on 2021-11-30 00:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('patients', '0010_alter_bills_owner'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tests',
            name='id',
            field=models.UUIDField(editable=False, primary_key=True, serialize=False),
        ),
    ]
